function* lexer_mark (){
    yield* lexer_mark_symbol ();
    yield* lexer_mark_number ();
    yield* lexer_mark_folder ();
    yield* lexer_mark_extral ();
}

function* lexer_mark_symbol () {
    //using default
    //yield [SC_MARGIN_FORE, 01, 0xFF222827];
    //yield [SC_MARGIN_BACK, 01, 0xFFE0E0E0];
    //yield [SC_MARGIN_COLOUR, 01, 0xFFE0E0E0];

    yield [SCI_SETMARGINTYPEN,  0x00, SC_MARGIN_SYMBOL];
    yield [SCI_SETMARGINWIDTHN, 0x00, 16];
    yield [SCI_SETMARGINMASKN,  0x00, 0x00];
	yield [SCI_SETMARGINSENSITIVEN, 0x00, 0x01];

    yield [SCI_SETMARGINTYPEN,      0x02, SC_MARGIN_SYMBOL];
    yield [SCI_SETMARGINWIDTHN,     0x02, 16];
    yield [SCI_SETMARGINMASKN,      0x02, parseInt("00000000111111111111111111111111", 2)];
	yield [SCI_SETMARGINSENSITIVEN, 0x02, 0x01];
}

function* lexer_mark_number () {
    yield [SCI_SETMARGINTYPEN,      0x01, SC_MARGIN_SYMBOL];
    yield [SCI_SETMARGINWIDTHN,     0x01, 0];
    yield [SCI_SETMARGINMASKN,      0x01, 0x00];
	yield [SCI_SETMARGINSENSITIVEN, 0x01, 0x01];
}

function* lexer_mark_folder () {
    //yield [SC_MARGIN_FORE, 01, 0xFF222827];
    //yield [SC_MARGIN_BACK, 01, 0xFFE0E0E0];
    //yield [SC_MARGIN_COLOUR, 01, 0xFFE0E0E0];

    yield [SCI_SETMARGINTYPEN,      0x03, SC_MARGIN_SYMBOL];
    yield [SCI_SETMARGINMASKN,      0x03, SC_MASK_FOLDERS];
    yield [SCI_SETMARGINWIDTHN,     0x03, 16];
	yield [SCI_SETMARGINSENSITIVEN, 0x03, 0x01];

    //yield [SCI_SETFOLDMARGINCOLOUR, 0x01, 0x222827];
    //yield [SCI_SETFOLDMARGINHICOLOUR, 0x01, 0x0B00FF];

    yield [SCI_MARKERDEFINE, SC_MARKNUM_FOLDEROPEN, SC_MARK_MINUS];
    yield [SCI_MARKERSETFORE, SC_MARKNUM_FOLDEROPEN, 0xFF222827];
    yield [SCI_MARKERSETBACK, SC_MARKNUM_FOLDEROPEN, 0xFFE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, SC_MARKNUM_FOLDEROPEN, 0xFF];

    yield [SCI_MARKERDEFINE, SC_MARKNUM_FOLDER, SC_MARK_PLUS];
    yield [SCI_MARKERSETFORE, SC_MARKNUM_FOLDER, 0x222827];
    yield [SCI_MARKERSETBACK, SC_MARKNUM_FOLDER, 0xE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, SC_MARKNUM_FOLDER, 0xFF];

    yield [SCI_MARKERDEFINE, SC_MARKNUM_FOLDERSUB, SC_MARK_EMPTY];
    yield [SCI_MARKERSETFORE, SC_MARKNUM_FOLDERSUB, 0x222827];
    yield [SCI_MARKERSETBACK, SC_MARKNUM_FOLDERSUB, 0xE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, SC_MARKNUM_FOLDERSUB, 0xFF];

    yield [SCI_MARKERDEFINE, SC_MARKNUM_FOLDERTAIL, SC_MARK_EMPTY];
    yield [SCI_MARKERSETFORE, SC_MARKNUM_FOLDERTAIL, 0x222827];
    yield [SCI_MARKERSETBACK, SC_MARKNUM_FOLDERTAIL, 0xE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, SC_MARKNUM_FOLDERTAIL, 0xFF];

    yield [SCI_MARKERDEFINE, SC_MARKNUM_FOLDEREND, SC_MARK_EMPTY];
    yield [SCI_MARKERSETFORE, SC_MARKNUM_FOLDEREND, 0x222827];
    yield [SCI_MARKERSETBACK, SC_MARKNUM_FOLDEREND, 0xE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, SC_MARKNUM_FOLDEREND, 0xFF];

    yield [SCI_MARKERDEFINE, SC_MARKNUM_FOLDEROPENMID, SC_MARK_EMPTY];
    yield [SCI_MARKERSETFORE, SC_MARKNUM_FOLDEROPENMID, 0x222827];
    yield [SCI_MARKERSETBACK, SC_MARKNUM_FOLDEROPENMID, 0xE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, SC_MARKNUM_FOLDEROPENMID, 0xFF];

    //yield [SCI_MARKERDEFINE, SC_MARKNUM_FOLDERMIDTAIL, SC_MARK_BOOKMARK];
    yield [SCI_MARKERDEFINE, SC_MARKNUM_FOLDERMIDTAIL, SC_MARK_EMPTY];
    yield [SCI_MARKERSETFORE, SC_MARKNUM_FOLDERMIDTAIL, 0x222827];
    yield [SCI_MARKERSETBACK, SC_MARKNUM_FOLDERMIDTAIL, 0xE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, SC_MARKNUM_FOLDERMIDTAIL, 0xFF];

    // The highlight is disabled for plus/minus.
    yield [SCI_MARKERENABLEHIGHLIGHT, 0x00, 0x00];
}

function* lexer_mark_extral () {
    yield [SCI_MARKERDEFINE, 1, SC_MARK_BOOKMARK];
    yield [SCI_MARKERSETFORE, 1, 0xFF222827];
    yield [SCI_MARKERSETBACK, 1, 0xFFE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, 1, 0xFF];

    yield [SCI_MARKERDEFINE, 2, SC_MARK_CIRCLE];
    yield [SCI_MARKERSETFORE, 2, 0xFF222827];
    yield [SCI_MARKERSETBACK, 2, 0xFFE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, 1, 0xFF];

    yield [SCI_MARKERDEFINE, 4, SC_MARK_ARROW];
    yield [SCI_MARKERSETFORE, 4, 0xFF222827];
    yield [SCI_MARKERSETBACK, 4, 0xFFE0E0E0];
    yield [SCI_MARKERSETBACKSELECTED, 4, 0xFF];
}

